clc
clear
addpath(genpath('D:\Users\danny\Documents\millerlab\bento\bentoMAT\bento'))
load('D:\Users\danny\Documents\millerlab\bento\example_data\20201020_Pop_Cage_004.mat')
params = struct( ...
    'monkey_name','Pop', ...
    'array_name','M1', ...
    'task_name','WM', ...
    'ran_by','KLB', ...
    'lab',1, ...
    'bin_width',0.001, ...
    'sorted',0, ...
    'requires_raw_emg',1);

base_dir = 'D:/Users/danny/Documents/millerlab/bento/example_data/Jango_IsoHoriz_UtahEMGs_042015_SN_003/';
% base_dir = pwd;
file_name = 'Jango_IsoHoriz_UtahEMGs_042015_SN_003.nev';
map_dir = 'Z:/limblab/lab_folder/Animal-Miscellany/Pop_18E3/Array Map Files/Implant_2020_01/6250-002086/';
map_name = 'SN 6250-002086.cmp';
save_dir = './';
data = raw_to_bento(base_dir, file_name, map_dir, map_name, params);
save_name = strcat(save_dir, file_name);
save(strcat(save_name, '.mat'),'data');